### PR TITLE
Soap

### PR DESCRIPTION
**Pull request by rashaler**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@rashaler This PR doesn't make sense to me. Why are you recommiting everything to master? All the relevant code for each connector is sorted into their own protected branches? Am I missing something here?

**Comment by superkhau** [comment]
This have been resolved. Closing.

**Pull request closed without merging**
